### ISSUE TITLE
Inability to daemonize server process

### ISSUE THREAD

**Issue by jchristi** [jubos/fake-s3#109]
I would like to be able to daemonize the server process so that I can create a proper init script.

**Comment by jcward10** [comment]
:+1:

**Comment by pickhardt** [comment]
Hi,

Thanks for the feature request.

For now, you should be able to use the instructions at http://stackoverflow.com/questions/525247/how-do-i-daemonize-an-arbitrary-script-in-unix

I'm closing this because I've created another issue to track the feature request. (I want to start marking the issues with titles as [Feature] or [Bug]) See also https://github.com/jubos/fake-s3/issues/176

**Comment by jchristi** [comment]
I have an outstanding PR for this: https://github.com/jubos/fake-s3/pull/115
