### ISSUE TITLE
aws-sdk

### ISSUE THREAD

**Issue by ksheurs** [jubos/fake-s3#12]
is there anyway to support aws-sdk? with the sdk we do not have access to establish_connection to specify host and port :(

**Comment by ddossot** [comment]
This is documented enough IMO. FWW I have no trouble using fake-s3 with AWS SDK. Consider closing.

**Comment by LinusU** [comment]
This is how I connect to fake-s3 inside a docker container. The thing to take extra note of is `s3ForcePathStyle: true` which makes specifying an ip in the `endpoint` okay, since it force the use of `http://host:port/bucket-name/...` instead of `http://bucket-name.host:port/`.

```javascript
return new AWS.S3({
  apiVersion: '2006-03-01',
  sslEnabled: false,
  accessKeyId: 'x',
  secretAccessKey: 'x',
  endpoint: resolveEnv('http://$S3_PORT_4569_TCP_ADDR:$S3_PORT_4569_TCP_PORT'),
  s3ForcePathStyle: true
});
```

**Comment by gabrielle27** [comment]
I was running into the timeout issue as well. I thought it was aws-sdk, but it was a problem in my paperlip config. The paperclip initializer expects `s3_host_name` instead of `s3_endpoint`.

**Comment by cesarandreu** [comment]
About a month ago I added [an example](https://github.com/jubos/fake-s3/wiki/Supported-Clients#nodejs) to the wiki, for any future searchers.

**Comment by pickhardt** [comment]
Closing because this is being discussed in multiple places, and this particular discussion is old.

For future reference, it should work if you spoof your /etc/hosts to point s3.amazonaws.com to localhost, and make sure you're using the latest versions of Fake S3 and the aws-sdk. If it doesn't, please open a new issue with an example of what you tried.
