### ISSUE TITLE
Files saved as folders

### ISSUE THREAD

**Issue by robzolkos** [jubos/fake-s3#131]
When uploading a file (using rails, carrierwave, fog) the uploaded files are saved as folders.

I've created a repo that reproduces the problem https://github.com/robzolkos/railsfakes3

There is another issue https://github.com/jubos/fake-s3/issues/126 that had a similar problem although using the forked version as commented in that issue did not work either.

**Comment by johannesboyne** [comment]
Hi @robzolkos I'm encountering the exact same problem,
did you find any solution?

**Comment by yuniersoad** [comment]
The same is happening to me while uploading a file using Cyberduck in OSX, if I go to the file system I find a folder instead of a file; curiously enough if I download the file using the same client there is no problem with it.

**Comment by johannesboyne** [comment]
@yuniersoad I've started an other Fake S3 implementation because of this here: https://github.com/johannesboyne/gofakes3
It also handles metadata and uses a B+tree K/V-Datastore which is just a bit more like a real object-store from my point of view.
It is *not* complete but if you want to look at it, feel free to comment on it!
I've not checked it with Cyberduck though!

**Comment by yuniersoad** [comment]
@johannesboyne I've also been meaning to create a fake s3, but on top of the file system maybe it won't be the greatest performance but it'll do for testing stuff. I'll check your project, Go seems like an exciting language to learn this days. 
I've noticed that this project doesn't use the existing folders & files in the root directory as buckets & objects only what you add through the API; Is there an option to override this?

**Comment by johannesboyne** [comment]
@yuniersoad I didn't want to have the file-system as "storage" because of the following considerations:
- Possibility to store Metadata
- Project switching (--> just rename the 1 single file)
- Folder traversal is "a bit" more complex than K/V scanning through BoltDB (the storage)

But I can see some "use-cases" for it, maybe I'll add it in the future. But especially because of the Metadata stuff I do not need it for our projects, since we're using Metadata information quite heavily.
Feel free to add an issue, just so I do not forget about this ;)

**Comment by andrewgaul** [comment]
@yuniersoad [S3Proxy](https://github.com/andrewgaul/s3proxy) provides functionality similar to fakes3 and can use existing files.

@johannesboyne File systems can support S3 metadata via extended attributes.

**Comment by johannesboyne** [comment]
@andrewgaul That's pretty cool! I haven't used `extended attributes` but it looks good.

**Comment by bradharms** [comment]
Hi,

I just started using FakeS3 today and noticed the same thing about files being saved as folders. I was worried that the data wasn't being saved but then I noticed that the folders all contain a hidden sub-folder with a name like '.fakes3_metadataFFF'. This folder contains the file content as well as meta data in files called 'content' and 'metadata', respectively. So, I would assume this is really just an implementation detail? Otherwise maybe I'm not understanding the purpose of this bug report?

**Comment by robzolkos** [comment]
I _think_ I figured this out.   FakeS3 is meant to be used as a server, to mimick S3.  If you try and retrieve the file via the http interface then it works as S3 does.  How it saves on the local file system is an implementation detail (just as we don't know or care how a file saves on real S3).   If you store and retrieve files via the http interface then it works great.

**Comment by valberg** [comment]
Might be an idea to include this in the README. I was quite confused until finding this issue 😄
