### ISSUE TITLE
License change in version upgrade

### ISSUE THREAD

**Issue by jakajancar** [jubos/fake-s3#187]
Hey,

First of all, thanks for fakes3! I imagine maintaining it is quite an effort, and I hope you succeed in getting compensated for it, especially given how much money it's probably saving on AWS and developer productivity.

However... :)

I expect there will be many who will upgrade the version of fakes3 and, as a consequence, accidentally get a dependency with a license that is not pre-approved by their organization.

Heck, I'm not even sure if using fakes3 is still allowed without paying. The [website](https://supportedsource.org/projects/fake-s3) says:

> What is Supported Source?
> Supported Source is platform for software projects to sell licenses. These may be open source projects selling a commercial license for their entire project (**dual licensing**), a license for a pro version of their project (open core), or a **non-open source** project selling licenses for their project.

I'm not sure which fakes3 falls under.

Perhaps better approaches would be

  * dual-licensing under MIT and Supported source if you've chosen dual-licensing, or
  * changing the name of the package (fakes3 v2?) to force a manual intervention + a strong link from v1 to v2?

Anyways, just wanted to bring it to your attention...

Jaka

**Comment by pickhardt** [comment]
Hi Jaka,

Fake S3 isn't being dual licensed. Dual licensing with a MIT license wouldn't accomplish anything since the MIT license is already business friendly. Dual licensing is better suited for something like the AGPL. We're offering v1 under the new license, which isn't open source.

However, if you had version 0.2.5, you're free to continue using the old version under the previous MIT license. Just specify a version in your Gemfile. The version switched to v1 with the license change, which came with a post-install notice as well. We've considered stronger ways beyond the post-install message, but for now this seemed like the best approach. Your second idea about changing the package name is one such stronger approach.

Some companies have already acquired the new license, however I expect there are many ignoring the notice. Without a way to know who's using the project, it's hard to reach out to let them know beyond the post-install message.

If a company's serious about license compliance, there's various software they can use to automatically detect licenses of their libraries, like LicenseFinder. Larger companies typically have something like this. The license was updated in Fake S3's Gemspec so any organization with automated compliance software would have additional notice beyond the post-install message.

Hope that helps!

**Comment by freeall** [comment]
I'm quite confused about this. Am I not allowed to use fake-s3 without paying for it? If that's the case, then I think you should make it more clear in https://github.com/jubos/fake-s3/#licensing and also on https://supso.org/faq which I think is also run by you guys?

**Comment by pickhardt** [comment]
Depends on your organization size. If you're an individual or small company, it's free, otherwise we're asking the companies to buy a license. The goal is to make the project more sustainable than it otherwise would be, i.e. abandoned like it used to be. The FAQ link you linked is for Super Source generally, while the project page at https://supso.org/projects/fake-s3 contains some questions and answers on the right sidebar that explain it more in the context of the project.

**Comment by freeall** [comment]
I noticed that you removed the MIT license, but I couldn't find an issue/discussion about it. Did you get permission from all contributors before doing so, and is that public anywhere?

Not trying to be a douche, but I've just never seen a (technically) open source project without free (as in free beer) usage before.

**Comment by pickhardt** [comment]
It was over email, with the CLA signed electronically. It's not an open source license any longer although it's still free for individuals and small companies. You've probably seen other projects forked and relicensed, maybe taking on a new name at the same time. This is similar except we kept the name and updated the major version at the time.

**Comment by benatkin** [comment]
This has no doubt resulted in people violating your license without even knowing it. It's fine if you want to do that but I'm not thrilled with Rubygems being involved in this dubious endeavor.

**Comment by shigemk2** [comment]
Which license can we use when we develop OSS library with current fake-s3?

Can we use MIT license on the library with fake-s3?

**Comment by pickhardt** [comment]
You can still use it with an OSS library, we just are asking the end users to register to get the Fake S3 license.

**Comment by shigemk2** [comment]
What do you mean end users?

1. people using fake-s3
2. people using OSS library using fake-s3

Does the people that have to register super source include people using OSS library using fake-s3?

**Comment by pickhardt** [comment]
End user is the person who eventually uses the product. It depends on whether the people using the OSS library are also using Fake S3, in which case they'd want to register to get a license.
